### PR TITLE
Clear output folder setting, readme changes, Dockerfile changes

### PR DESCRIPTION
**Pull request by m-a-x-s-e-e-l-i-g**
- Added setting to clear output folder.
- Some readme changes that work for me
- Undone some changes to Dockerfile to make it work
I couldn't build with the previous version of the Dockerfile:
On `RUN apt-get install -y google-chrome-stable=${CHROME_VERSION}` in `Dockerfile:10`
I received: `ERROR: failed to solve: process "/bin/sh -c apt-get install -y google-chrome-stable=${CHROME_VERSION}" did not complete successfully: exit code: 100`
image

### CODE REVIEW

**Comment by a-nau** [comment]
Thanks for the PR @m-a-x-s-e-e-l-i-g! At first glance:

- Dockerfile works locally for me and also in Github CI. Are you using a very old version of Docker? Or did you maybe try to build an older version? I prefer it as is, since it fixes the Chrome version and prevents future incompatibilities.
- To clean up the folder I would just remove it and create a new one, that's only 2 lines of code. Also `pathlib` is much more intuitiv than `os`, you should check it out. Also we don't need a separate file in the tools folder for this, I think.
- haven't tried the button in the UI, but very good idea!
- maybe split up build and run in the readme again?

**Comment by m-a-x-s-e-e-l-i-g** [comment]
- Using Docker Engine v24.0.2 build cb74dfc, trying to build this current branch without the changes in Dockerfile. Both on Windows 10 and 11.
  - Tried building from Windows
  - Tried building from WSL2 with Ubuntu 22.04.2 LTS
- I'll try out `pathlib`, thanks!
- I'll split up the build and run in readme

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Sorry, I didn't read the full error before:
```
=> ERROR [ 6/14] RUN apt-get install -y google-chrome-stable=114.0.5735.198-1                                                                                          1.5s 
------
 > [ 6/14] RUN apt-get install -y google-chrome-stable=114.0.5735.198-1:
0.471 Reading package lists...
1.242 Building dependency tree...
1.414 Reading state information...
1.420 Package google-chrome-stable is not available, but is referred to by another package.
1.420 This may mean that the package is missing, has been obsoleted, or
1.420 is only available from another source
1.420
1.422 E: Version '114.0.5735.198-1' for 'google-chrome-stable' was not found
```
It seems that older versions get removed from their [PPA](https://www.ubuntuupdates.org/ppa/google_chrome?dist=stable). 
- Fixed this issue in last commit.
- I split up the build and run in readme
- I'll try out `pathlib`, thanks!

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Sorry, I didn't read the full error before:
```
=> ERROR [ 6/14] RUN apt-get install -y google-chrome-stable=114.0.5735.198-1                                                                                          1.5s 
------
 > [ 6/14] RUN apt-get install -y google-chrome-stable=114.0.5735.198-1:
0.471 Reading package lists...
1.242 Building dependency tree...
1.414 Reading state information...
1.420 Package google-chrome-stable is not available, but is referred to by another package.
1.420 This may mean that the package is missing, has been obsoleted, or
1.420 is only available from another source
1.420
1.422 E: Version '114.0.5735.198-1' for 'google-chrome-stable' was not found
```
It seems that older versions get removed from their [PPA](https://www.ubuntuupdates.org/ppa/google_chrome?dist=stable). 

- Fixed this issue in last commit.
- I split up the build and run in readme
- I'll try out `pathlib`, thanks!

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Removing the complete folder and recreating it using Pathlib and shutil could result in
`OSError: [Errno 16] Device or resource busy: '/usr/src/app/output'`
You can't keep your output or subdirectories open without having to catch the error.

I moved the function to frontend.py

**Comment by a-nau** [comment]
Cool, thanks! Looks good :) Sorry for the delay...

**Pull request merged**
